In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
from sklearn.datasets import load_boston

In [6]:
boston=load_boston()

e:\BostonHousePricing\myenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing datase

In [7]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [8]:
# lets check the description of dataset
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [9]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [10]:
print(boston.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [11]:
df=pd.DataFrame(boston.data,columns=[boston.feature_names])

In [12]:
df.head()

CRIM    ZN INDUS CHAS    NOX     RM   AGE     DIS  RAD    TAX PTRATIO  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0    15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0    17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0    17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0    18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0    18.7   

        B LSTAT  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [13]:
df["target"]=boston.target

In [14]:
df.head()

CRIM    ZN INDUS CHAS    NOX     RM   AGE     DIS  RAD    TAX PTRATIO  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0    15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0    17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0    17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0    18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0    18.7   

        B LSTAT target  
0  396.90  4.98   24.0  
1  396.90  9.14   21.6  
2  392.83  4.03   34.7  
3  394.63  2.94   33.4  
4  396.90  5.33   36.2

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   (CRIM,)     506 non-null    float64
 1   (ZN,)       506 non-null    float64
 2   (INDUS,)    506 non-null    float64
 3   (CHAS,)     506 non-null    float64
 4   (NOX,)      506 non-null    float64
 5   (RM,)       506 non-null    float64
 6   (AGE,)      506 non-null    float64
 7   (DIS,)      506 non-null    float64
 8   (RAD,)      506 non-null    float64
 9   (TAX,)      506 non-null    float64
 10  (PTRATIO,)  506 non-null    float64
 11  (B,)        506 non-null    float64
 12  (LSTAT,)    506 non-null    float64
 13  (target,)   506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [16]:
df.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
target     0
dtype: int64

In [19]:
df.head()

CRIM    ZN INDUS CHAS    NOX     RM   AGE     DIS  RAD    TAX PTRATIO  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0    15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0    17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0    17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0    18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0    18.7   

        B LSTAT target  
0  396.90  4.98   24.0  
1  396.90  9.14   21.6  
2  392.83  4.03   34.7  
3  394.63  2.94   33.4  
4  396.90  5.33   36.2

In [20]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT      target  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

## EDA


In [ ]:
df.corr()["target"]

In [ ]:
import seaborn as sn

In [ ]:
plt.figure(figsize=(12,12))
sn.heatmap(df.corr(),annot=True)

In [ ]:
plt.scatter(df["CRIM"],df["target"])

In [ ]:
plt.scatter(df["RM"],df["target"])

In [ ]:
sn.regplot(x="RM",y="target",data=df)

In [ ]:
sn.regplot(x="LSTAT",y="target",data=df)

In [ ]:
sn.regplot(x="PTRATIO",y="target",data=df)

In [22]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [23]:
X.head()

CRIM    ZN INDUS CHAS    NOX     RM   AGE     DIS  RAD    TAX PTRATIO  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0    15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0    17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0    17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0    18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0    18.7   

        B LSTAT  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [24]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: (target,), dtype: float64

In [25]:
X.shape

(506, 13)

In [26]:
y.shape

(506,)

In [27]:
from sklearn.model_selection import train_test_split


In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [29]:
X_train.head()

CRIM   ZN  INDUS CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
5     0.02985  0.0   2.18  0.0  0.458  6.430  58.7  6.0622   3.0  222.0   
116   0.13158  0.0  10.01  0.0  0.547  6.176  72.5  2.7301   6.0  432.0   
45    0.17142  0.0   6.91  0.0  0.448  5.682  33.8  5.1004   3.0  233.0   
16    1.05393  0.0   8.14  0.0  0.538  5.935  29.3  4.4986   4.0  307.0   
468  15.57570  0.0  18.10  0.0  0.580  5.926  71.0  2.9084  24.0  666.0   

    PTRATIO       B  LSTAT  
5      18.7  394.12   5.21  
116    17.8  393.30  12.04  
45     17.9  396.90  10.21  
16     21.0  386.85   6.58  
468    20.2  368.74  18.13

In [30]:
X_test.head()

CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
173  0.09178   0.0   4.05  0.0  0.510  6.416  84.1  2.6463   5.0  296.0   
274  0.05644  40.0   6.41  1.0  0.447  6.758  32.9  4.0776   4.0  254.0   
491  0.10574   0.0  27.74  0.0  0.609  5.983  98.8  1.8681   4.0  711.0   
72   0.09164   0.0  10.81  0.0  0.413  6.065   7.8  5.2873   4.0  305.0   
452  5.09017   0.0  18.10  0.0  0.713  6.297  91.8  2.3682  24.0  666.0   

    PTRATIO       B  LSTAT  
173    16.6  395.50   9.04  
274    17.6  396.90   3.53  
491    20.1  390.11  18.07  
72     19.2  390.91   5.52  
452    20.2  385.09  17.27

In [31]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
X_train=scale.fit_transform(X_train)
X_test=scale.transform(X_test)

e:\BostonHousePricing\myenv\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
e:\BostonHousePricing\myenv\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
e:\BostonHousePricing\myenv\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


In [32]:
import pickle
pickle.dump(scale,open('scaling1.pkl','wb'))

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
from sklearn.linear_model import LinearRegression


In [ ]:
model=LinearRegression()

In [ ]:
model.fit(X_train,y_train)

In [ ]:
print(model.coef_)

In [ ]:
print(model.intercept_)

In [ ]:
model.get_params()

In [ ]:
pred=model.predict(X_test)

In [ ]:
plt.scatter(y_test,pred)

In [ ]:
from sklearn.metrics import r2_score,confusion_matrix,ad
r2_score(y_test,pred)

In [ ]:
sn.displot(y_test-pred,kind="kde")

# So we can see there are outliers

In [ ]:
plt.scatter(pred,y_test-pred)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test,pred))

In [ ]:
score= r2_score(y_test,pred)

In [ ]:
#adjusted r2?
1-(1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

In [ ]:
boston.data[0].shape

In [ ]:
boston.data[0].reshape(1,-1)

In [ ]:
scaled_data=scale.transform(boston.data[0].reshape(1,-1))
model.predict(scaled_data)

In [ ]:
import pickle

In [ ]:
pickle.dump(model,open('reg_boston.pkl','wb'))

In [ ]:
pickle_f=pickle.load(open('reg_boston.pkl','rb'))
pickle_f.predict(scaled_data)